/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppAppProjectsImport } from './routes/_app/app/projects/*'
import { Route as AppAppProjectsProjectIdImport } from './routes/_app/app/projects/$projectId'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppAppProjectsRoute = AppAppProjectsImport.update({
  id: '/app/projects/*',
  path: '/app/projects/*',
  getParentRoute: () => AppRoute,
} as any)

const AppAppProjectsProjectIdRoute = AppAppProjectsProjectIdImport.update({
  id: '/app/projects/$projectId',
  path: '/app/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/app/projects/$projectId': {
      id: '/_app/app/projects/$projectId'
      path: '/app/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppAppProjectsProjectIdImport
      parentRoute: typeof AppImport
    }
    '/_app/app/projects/*': {
      id: '/_app/app/projects/*'
      path: '/app/projects/*'
      fullPath: '/app/projects/*'
      preLoaderRoute: typeof AppAppProjectsImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppAppProjectsProjectIdRoute: typeof AppAppProjectsProjectIdRoute
  AppAppProjectsRoute: typeof AppAppProjectsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppProjectsProjectIdRoute: AppAppProjectsProjectIdRoute,
  AppAppProjectsRoute: AppAppProjectsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/app/projects/$projectId': typeof AppAppProjectsProjectIdRoute
  '/app/projects/*': typeof AppAppProjectsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/app/projects/$projectId': typeof AppAppProjectsProjectIdRoute
  '/app/projects/*': typeof AppAppProjectsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/app/projects/$projectId': typeof AppAppProjectsProjectIdRoute
  '/_app/app/projects/*': typeof AppAppProjectsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/app/projects/$projectId' | '/app/projects/*'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/app/projects/$projectId' | '/app/projects/*'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/app/projects/$projectId'
    | '/_app/app/projects/*'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/app/projects/$projectId",
        "/_app/app/projects/*"
      ]
    },
    "/_app/app/projects/$projectId": {
      "filePath": "_app/app/projects/$projectId.tsx",
      "parent": "/_app"
    },
    "/_app/app/projects/*": {
      "filePath": "_app/app/projects/*.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
